wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688357605.097606
    t:
      1:
      - 1
      - 5
      - 12
      - 30
      - 45
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 30
      - 45
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
env_name:
  desc: null
  value: ant
seed:
  desc: null
  value: 1111
torch_deterministic:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
wandb_run_name:
  desc: null
  value: energy_1000_paper_ppga_ant_seed_1111
wandb_group:
  desc: null
  value: paper
wandb_project:
  desc: null
  value: PPGA
env_batch_size:
  desc: null
  value: 3000
report_interval:
  desc: null
  value: 5
rollout_length:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
anneal_lr:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 8
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
clip_value_coef:
  desc: null
  value: 0.2
entropy_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 2.0
max_grad_norm:
  desc: null
  value: 1.0
target_kl:
  desc: null
  value: null
normalize_obs:
  desc: null
  value: true
normalize_returns:
  desc: null
  value: true
value_bootstrap:
  desc: null
  value: false
weight_decay:
  desc: null
  value: null
clip_obs_rew:
  desc: null
  value: false
num_emitters:
  desc: null
  value: 1
grid_size:
  desc: null
  value: 7
num_dims:
  desc: null
  value: 4
popsize:
  desc: null
  value: 300
log_arch_freq:
  desc: null
  value: 10
save_scheduler:
  desc: null
  value: true
load_scheduler_from_cp:
  desc: null
  value: null
load_archive_from_cp:
  desc: null
  value: null
total_iterations:
  desc: null
  value: 2000
dqd_algorithm:
  desc: null
  value: cma_maega
expdir:
  desc: null
  value: ./experiments/paper_ppga_ant
save_heatmaps:
  desc: null
  value: true
use_surrogate_archive:
  desc: null
  value: false
sigma0:
  desc: null
  value: 3.0
restart_rule:
  desc: null
  value: no_improvement
calc_gradient_iters:
  desc: null
  value: 10
move_mean_iters:
  desc: null
  value: 10
archive_lr:
  desc: null
  value: 0.1
threshold_min:
  desc: null
  value: -500.0
take_archive_snapshots:
  desc: null
  value: true
adaptive_stddev:
  desc: null
  value: true
use_cvt_archive:
  desc: null
  value: true
cvt_cells:
  desc: null
  value: 1000
cvt_samples:
  desc: null
  value: 100000
cvt_k_means_kwargs:
  desc: null
  value: ''
cvt_use_kd_tree:
  desc: null
  value: true
cvt_ckdtree_kwargs:
  desc: null
  value: ''
is_energy_measures:
  desc: null
  value: true
batch_size:
  desc: null
  value: 384000
num_envs:
  desc: null
  value: 3000
minibatch_size:
  desc: null
  value: 48000
obs_shape:
  desc: null
  value:
  - 87
action_shape:
  desc: null
  value:
  - 8
