wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699326342.058388
    t:
      1:
      - 1
      - 5
      - 12
      - 30
      - 45
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 30
      - 45
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
env_name:
  desc: null
  value: pong
seed:
  desc: null
  value: 1111
torch_deterministic:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
wandb_run_name:
  desc: null
  value: pong-test
wandb_group:
  desc: null
  value: qdrl
wandb_project:
  desc: null
  value: PPGA
report_interval:
  desc: null
  value: 5
total_timesteps:
  desc: null
  value: 10
env_type:
  desc: null
  value: envpool
env_batch_size:
  desc: null
  value: 3000
num_workers:
  desc: null
  value: 4
envs_per_worker:
  desc: null
  value: 1
rollout_length:
  desc: null
  value: 128
learning_rate:
  desc: null
  value: 0.001
anneal_lr:
  desc: null
  value: true
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
num_minibatches:
  desc: null
  value: 8
update_epochs:
  desc: null
  value: 4
norm_adv:
  desc: null
  value: true
clip_coef:
  desc: null
  value: 0.2
clip_value_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
entropy_coef:
  desc: null
  value: 0.0
vf_coef:
  desc: null
  value: 2.0
max_grad_norm:
  desc: null
  value: 1.0
target_kl:
  desc: null
  value: null
normalize_obs:
  desc: null
  value: true
normalize_returns:
  desc: null
  value: true
value_bootstrap:
  desc: null
  value: false
weight_decay:
  desc: null
  value: null
num_dims:
  desc: null
  value: 5
is_energy_measures:
  desc: null
  value: true
clip_obs_rew:
  desc: null
  value: false
gym_id:
  desc: null
  value: Pong-v5
batch_size:
  desc: null
  value: 384000
num_envs:
  desc: null
  value: 3000
num_emitters:
  desc: null
  value: 1
envs_per_model:
  desc: null
  value: 3000
minibatch_size:
  desc: null
  value: 48000
obs_shape:
  desc: null
  value:
  - 4
  - 84
  - 84
action_shape:
  desc: null
  value:
  - 6
